[package]
name = "battleship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
crossterm = { version = "0.26.1", features = ["event-stream"] }
tui = "0.19.0"
